# Ethtool offload configuration

- name: NIC OFFLOAD SETTINGS
  hosts: localhost

  vars:
    INTERFACES:
      - enp6s0f0
      - enp6s0f1

  tasks:

    - name: APPLY HARDWARE OFFLOAD SETTINGS

      block:
        - name: ENABLING HARDWARE RX-VLAN OFFLOADING
          command: /sbin/ethtool -K {{ item }} rxvlan off
          loop: "{{ INTERFACES }}"

        - name: ENABLING HARDWARE TX-VLAN OFFLOADING
          command: /sbin/ethtool -K {{ item }} txvlan off
          loop: "{{ INTERFACES }}"

        - name: DISABLING HARDWARE RX CHECKSUM OFFLOADING
          command: /sbin/ethtool -K {{ item }} rx off
          loop: "{{ INTERFACES }}"

        - name: DISABLING HARDWARE TX CHECKSUM OFFLOADING
          command: /sbin/ethtool -K {{ item }} tx off
          loop: "{{ INTERFACES }}"

        - name: DISABLING HARDWARE [TSO] TCP SEGMENTATION OFFLOADING
          command: /sbin/ethtool -K {{ item }} tso off
          loop: "{{ INTERFACES }}"

        - name: DISABLING HARDWARE [GSO] GENERIC SEGMENTATION OFFLOADING
          command: /sbin/ethtool -K {{ item }} gso off
          loop: "{{ INTERFACES }}"

        - name: DISABLING HARDWARE [GRO] GENERIC RECEIVE OFFLOADING
          command: /sbin/ethtool -K {{ item }} gro off
          loop: "{{ INTERFACES }}"

        - name: DISABLING HARDWARE [LRO] LARGE RECEIVE OFFLOADING
          command: /sbin/ethtool -K {{ item }} lro off
          loop: "{{ INTERFACES }}"


